import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { applyV25GatewayPatches } from "./lib/v25-gateway-patches.mjs";
import { applyV255GatewayPatches } from "./lib/v25-5-gateway-patches.mjs";
import { applyV256GatewaySecurityPatches } from "./lib/v25-6-gateway-security-patches.mjs";
import { applyV2512GatewaySocialPlatformPatches } from "./lib/v25-12-social-platform-patches.mjs";
import { applyV264TenantReliabilityPatches } from "./lib/v26-4-tenant-reliability-patches.mjs";
import { applyV2618GatewayAlwaysOnPatches } from "./lib/v26-18-always-on-patches.mjs";
import { applyV26181RuntimeStabilityPatches } from "./lib/v26-18-1-runtime-stability-patches.mjs";
import { applyV2637GatewayGuardianPatches } from "./lib/v26-37-guardian-24x7-patches.mjs";

const here=path.dirname(fileURLToPath(import.meta.url));
const corePath=path.join(here,"gateway.mjs");
const generatedPath=path.join(here,".gateway-v25.generated.mjs");
const source=await readFile(corePath,"utf8");
let patched=applyV25GatewayPatches(source);
patched=applyV255GatewayPatches(patched);
patched=applyV256GatewaySecurityPatches(patched);
patched=applyV2512GatewaySocialPlatformPatches(patched);
patched=applyV264TenantReliabilityPatches(patched);
patched=applyV2618GatewayAlwaysOnPatches(patched);
patched=applyV26181RuntimeStabilityPatches(patched);
patched=applyV2637GatewayGuardianPatches(patched);
await writeFile(generatedPath,patched,"utf8");
await import(`${pathToFileURL(generatedPath).href}?v25=${Date.now()}`);
