import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { applyV24ServerPatches } from "./lib/v24-server-patches.mjs";
import { applyV24CloudPatches } from "./lib/v24-cloud-patches.mjs";
import { applyV241ServerPatches } from "./lib/v24-1-server-patches.mjs";
import { applyV254ServerPatches } from "./lib/v25-4-server-patches.mjs";
import { applyV257FormPatches } from "./lib/v25-7-form-patches.mjs";
import { applyV256SecurityPatches } from "./lib/v25-6-security-patches.mjs";
import { applyV258ReportAiPatches } from "./lib/v25-8-report-ai-patches.mjs";
import { applyV259SupportPatches } from "./lib/v25-9-support-patches.mjs";
import { applyV2510SocialPatches } from "./lib/v25-10-social-patches.mjs";
import { applyV2511OmnichannelPatches } from "./lib/v25-11-omnichannel-patches.mjs";
import { applyV2512SocialPlatformPatches } from "./lib/v25-12-social-platform-patches.mjs";
import { applyV262WhatsappPatches } from "./lib/v26-2-whatsapp-patches.mjs";
import { applyV263QrRecoveryPatches } from "./lib/v26-3-qr-recovery-patches.mjs";
import { applyV264PlatformReliabilityCatalogPatches } from "./lib/v26-4-platform-reliability-catalog-patches.mjs";
import { applyV265MediaReliabilityPatches } from "./lib/v26-5-media-reliability-patches.mjs";
import { applyV266MediaRetryPatches } from "./lib/v26-6-media-retry-patches.mjs";
import { applyV268WhatsappEditPatches } from "./lib/v26-8-whatsapp-edit-patches.mjs";
import { applyV269AccessControlStable } from "./lib/v26-9-access-control-wrapper.mjs";
import { applyV2610LiveSupportBotLinePatches } from "./lib/v26-10-live-support-bot-lines-patches.mjs";
import { applyV2611MessageReliabilityPatches } from "./lib/v26-11-message-reliability-patches.mjs";
import { applyV26111MessageQueueSafetyPatches } from "./lib/v26-11-1-message-queue-safety-patches.mjs";
import { applyV2615WhatsappWatchdogPatches } from "./lib/v26-15-whatsapp-watchdog-patches.mjs";
import { applyV2616NewContactIntakePatches } from "./lib/v26-16-new-contact-intake-patches.mjs";
import { applyV2617ChatRefreshPatches } from "./lib/v26-17-chat-refresh-patches.mjs";
import { applyV2620AutoBranchRoutingStable } from "./lib/v26-20-auto-branch-routing-wrapper.mjs";
import { applyV2621CoreUiPatches, applyV2621InboxUiPatches, applyV2621ServerPatches } from "./lib/v26-21-chat-scroll-bulk-deals-patches.mjs";
import { applyV2623CoreUiPatches, applyV2623ServerPatches } from "./lib/v26-23-deal-amount-patches.mjs";
import { applyV2624CoreUiPatches, applyV2624ServerPatches } from "./lib/v26-24-existing-client-direct-patches.mjs";
import { applyV2625CoreUiPatches } from "./lib/v26-25-agent-messaging-ux-patches.mjs";
import { applyV2626CoreUiPatches } from "./lib/v26-26-messaging-scroll-draft-fix-patches.mjs";
import { applyV2627CoreUiPatches } from "./lib/v26-27-drawer-history-scroll-patches.mjs";
import { applyV2628CoreUiPatches } from "./lib/v26-28-emoji-message-replies-patches.mjs";
import { applyV2628CoreFixPatches } from "./lib/v26-28-core-escape-fix-patches.mjs";
import { applyV2628ServerPatches } from "./lib/v26-28-message-replies-reliable-server-patches.mjs";
import { applyV2629CoreUiPatches, applyV2629ServerPatches } from "./lib/v26-29-agent-ownership-visibility-patches.mjs";
import { applyV2630CoreUiPatches, applyV2630ServerPatches } from "./lib/v26-30-mobile-location-patches.mjs";
import { applyV2631CoreUiPatches, applyV2631ServerPatches } from "./lib/v26-31-notifications-fair-leads-patches.mjs";
import { applyV2634ServerPatches } from "./lib/v26-34-workflow-stability-patches.mjs";
import { applyV2635AdPromotionContextPatches } from "./lib/v26-35-ad-promotion-context-patches.mjs";
import { applyV2636ZeroLossIncomingPatches } from "./lib/v26-36-zero-loss-incoming-patches.mjs";
import { applyV2637GuardianAppPatches } from "./lib/v26-37-guardian-24x7-patches.mjs";
import { applyV2638CoreUiPatches, applyV2638ServerPatches } from "./lib/v26-38-closed-recontact-patches.mjs";
import { applyV2639CoreUiPatches } from "./lib/v26-39-mobile-chat-layout-patches.mjs";
import { applyV2640CoreUiPatches } from "./lib/v26-40-definitive-mobile-touch-scroll-patches.mjs";
import { applyV2641CoreUiPatches } from "./lib/v26-41-progressive-chat-history-patches.mjs";
import { applyV2642CoreUiPatches } from "./lib/v26-42-dedicated-mobile-message-scroll-patches.mjs";
import { applyV2643CoreUiPatches } from "./lib/v26-43-simple-responsive-conversation-patches.mjs";
import { applyV2645CoreUiPatches } from "./lib/v26-45-deal-chat-unified-inbox-ui-patches.mjs";
import { applyV2646CoreUiPatches } from "./lib/v26-46-complete-mobile-recontact-patches.mjs";

const appDir = path.dirname(fileURLToPath(import.meta.url));
const corePath = path.join(appDir, "server-core.mjs");
const generatedPath = path.join(appDir, ".server-v24.generated.mjs");
const publicAppPath = path.join(appDir, "public", "app.js");
const publicInboxPath = path.join(appDir, "public", "v25-11.js");

function restoreGeneratedTemplates(source, startMarker, endMarker) {
  const start = source.indexOf(startMarker);
  const end = source.indexOf(endMarker, start + startMarker.length);
  if (start < 0 || end < 0 || end <= start) throw new Error(`No se pudo normalizar el bloque V24: ${startMarker}`);
  const block = source.slice(start, end).replaceAll("\\`", "`").replaceAll("\\${", "${");
  return source.slice(0, start) + block + source.slice(end);
}

// Las capas que modifican los bundles públicos deben ejecutarse antes de cargar V26.14,
// porque V26.14 captura y optimiza app.js/v25-11.js en memoria al importarse.
const publicAppSource = await readFile(publicAppPath, "utf8");
let patchedPublicApp = applyV2617ChatRefreshPatches(publicAppSource);
patchedPublicApp = applyV2621CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2623CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2624CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2625CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2626CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2627CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2628CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2628CoreFixPatches(patchedPublicApp);
patchedPublicApp = applyV2629CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2630CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2631CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2638CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2639CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2640CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2641CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2642CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2643CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2645CoreUiPatches(patchedPublicApp);
patchedPublicApp = applyV2646CoreUiPatches(patchedPublicApp);
if (patchedPublicApp !== publicAppSource) await writeFile(publicAppPath, patchedPublicApp, "utf8");

const publicInboxSource = await readFile(publicInboxPath, "utf8");
const patchedPublicInbox = applyV2621InboxUiPatches(publicInboxSource);
if (patchedPublicInbox !== publicInboxSource) await writeFile(publicInboxPath, patchedPublicInbox, "utf8");

const { applyV2614PerformancePatches } = await import("./lib/v26-14-performance-patches.mjs");

const source = await readFile(corePath, "utf8");
let patched = applyV24ServerPatches(source);
patched = applyV24CloudPatches(patched);
patched = applyV241ServerPatches(patched);
patched = applyV254ServerPatches(patched);
patched = restoreGeneratedTemplates(patched, "async function v24TranscribeMediaAttachment", "async function maybeReplyWithBot");
patched = restoreGeneratedTemplates(patched, "function v24ActiveObserverGrant", "app.post(\"/api/deals/:id/transfer\"");
patched = applyV257FormPatches(patched);
patched = applyV256SecurityPatches(patched);
patched = applyV258ReportAiPatches(patched);
patched = applyV259SupportPatches(patched);
patched = applyV2510SocialPatches(patched);
patched = applyV2511OmnichannelPatches(patched);
patched = applyV2512SocialPlatformPatches(patched);
patched = applyV262WhatsappPatches(patched);
patched = applyV263QrRecoveryPatches(patched);
patched = applyV264PlatformReliabilityCatalogPatches(patched);
patched = applyV265MediaReliabilityPatches(patched);
patched = applyV266MediaRetryPatches(patched);
patched = applyV268WhatsappEditPatches(patched);
patched = applyV269AccessControlStable(patched);
patched = applyV2610LiveSupportBotLinePatches(patched);
patched = applyV2611MessageReliabilityPatches(patched);
patched = applyV26111MessageQueueSafetyPatches(patched);
patched = applyV2614PerformancePatches(patched);
patched = applyV2615WhatsappWatchdogPatches(patched);
patched = applyV2616NewContactIntakePatches(patched);
patched = applyV2620AutoBranchRoutingStable(patched);
patched = applyV2621ServerPatches(patched);
patched = applyV2623ServerPatches(patched);
patched = applyV2624ServerPatches(patched);
patched = applyV2628ServerPatches(patched);
patched = applyV2629ServerPatches(patched);
patched = applyV2630ServerPatches(patched);
patched = applyV2631ServerPatches(patched);
patched = applyV2634ServerPatches(patched);
patched = applyV2635AdPromotionContextPatches(patched);
patched = applyV2636ZeroLossIncomingPatches(patched);
patched = applyV2637GuardianAppPatches(patched);
patched = applyV2638ServerPatches(patched);
await writeFile(generatedPath, patched, "utf8");
await import(`${pathToFileURL(generatedPath).href}?v24=${Date.now()}`);